/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../../360downloads/android-ndk-r21b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
#ifndef _Included_com_test_util_HttpKeyUtil
#define _Included_com_test_util_HttpKeyUtil
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_dt_sign_SignUtils_getPublicKey
        (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_dt_sign_SignUtils_getPrivateKey
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

